[package]
name = "listing_06_dice_game_vrf"
version = "0.1.0"
edition = "2024_07"

[dependencies]
cartridge_vrf = { path = "cartridge_vrf" }
starknet = "2.16.1"
openzeppelin_access = "=2.0.0"

[dev-dependencies]
snforge_std = "0.58.1"
assert_macros = "2.16.1"

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]
