[package]
name = "listing_99_01"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[cairo]

[dependencies]
starknet = ">=2.12.0"

[dev-dependencies]
snforge_std = "0.48.0"
assert_macros = "2.12.0"

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]
