[package]
name = "no_listing_09_match_catch_all"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[cairo]

[dependencies]

[dev-dependencies]
cairo_test = "2.12.0"
