[package]
name = "no_listing_04_hash_pedersen"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[cairo]
enable-gas = false

[dependencies]
cairo_execute = "2.12.0"


[[target.executable]]
name = "main"
function = "no_listing_04_hash_pedersen::main"
