[package]
name = "listing_99_13_storage_packing"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[executable]

[cairo]
enable-gas = false

[dependencies]
cairo_execute = "2.11.4"
starknet = ">=2.11.4"

[dev-dependencies]
cairo_test = "2.11.4"
