[package]
name = "listing_11_pausable_erc20"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
openzeppelin = "2.0.0"
openzeppelin_upgrades = "2.0.0"
starknet = ">=2.12.0"

[dev-dependencies]
snforge_std = "0.48.0"
assert_macros = "2.12.0"

[[target.starknet-contract]]
casm = true

[cairo]
enable-gas = true
