[package]
name = "no_listing_20_type_equal"
version = "0.1.0"
edition = "2024_07"
experimental-features = ["associated_item_constraints", "negative_impls"]

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[executable]

[cairo]
enable-gas = false

[dependencies]
cairo_execute = "2.11.4"
