[package]
name = "listing_99_15_randomness"
version = "0.1.0"
edition = "2023_11"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
pragma_lib = { git = "https://github.com/astraly-labs/pragma-lib" }
starknet = ">=2.5.3"