[package]
name = "listing_closures"
version = "0.1.0"
edition = "2024_07"

experimental-features = ["associated_item_constraints"]

[dependencies]
cairo_execute = "2.12.0"

[cairo]
enable-gas = false


[[target.executable]]
name = "main"
function = "listing_closures::main"
