[package]
name = "listing_99_02"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[cairo]

[dependencies]
starknet = ">=2.12.0"
