[package]
name = "no_listing_loop_recursion"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
cairo_execute = "2.13.1"

[lib]
sierra-text = true

[cairo]
enable-gas = false


[[target.executable]]
name = "examples_recursion_example_main"
function = "no_listing_loop_recursion::examples::recursion_example::main"

[[target.executable]]
name = "examples_loop_example_main_2"
function = "no_listing_loop_recursion::examples::loop_example::main"
