[package]
name = "listing_invalid_qmark"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[cairo]

[dependencies]
cairo_execute = "2.12.0"

[dev-dependencies]
cairo_test = "2.12.0"
