[package]
name = "no_listing_19_let_chains"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
cairo_execute = "2.13.1"

[cairo]
enable-gas = false


[[target.executable]]
name = "main"
function = "no_listing_19_let_chains::main"
