#!/bin/bash
# Bump the Cairo/Scarb and Starknet Foundry versions pinned throughout the book.
#
# Version strings live in four kinds of places:
#   1. .tool-versions              -- the asdf/mise pins CI reads
#   2. Scarb.toml / Cargo.toml     -- dependency constraints in every listing
#   3. Prose + code fences in src/, docs/, CLAUDE.md
#   4. Scarb.lock / Cargo.lock     -- NEVER edited here; regenerated by the toolchain
#
# Everything is matched with anchored patterns (`= "2.16.1"`, `scarb 2.16.1`, ...)
# rather than a bare version regex, because bare version-like digit runs also occur
# in Excalidraw coordinates, Sierra program dumps and gas counters.
#
# Usage:
#   scripts/bump-versions.sh --cairo 2.16.1:2.20.0 --foundry 0.58.1:0.62.1 [--dry-run]
#
# Either --cairo or --foundry may be omitted to bump only one of the two.

# SC2312: this script deliberately ignores the exit status of `find | sort`
# pipelines. `find` returns non-zero for unreadable paths (pruned build dirs,
# stale symlinks) that are not errors here, and under `set -e` a propagated
# status would abort a bump that is otherwise complete.
# shellcheck disable=SC2312

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${REPO_ROOT}"

CAIRO_OLD="" CAIRO_NEW="" FOUNDRY_OLD="" FOUNDRY_NEW=""
DRY_RUN=0

usage() {
	cat <<'EOF'
Usage: scripts/bump-versions.sh [options]

  --cairo   OLD:NEW   Bump the Cairo/Scarb version (e.g. 2.16.1:2.20.0).
                      Applies to scarb pins and to the crates whose versions
                      track the compiler: cairo_execute, cairo_test,
                      assert_macros, starknet, cairo-lang-*.
  --foundry OLD:NEW   Bump the Starknet Foundry version (e.g. 0.58.1:0.62.1).
                      Applies to the starknet-foundry pin and snforge_std.
  --dry-run           Report what would change without writing anything.
  -h, --help          Show this help.

Not handled by this script (deliberately):
  * Scarb.lock / Cargo.lock      -- run `scarb fetch` / `cargo update` instead.
  * llms-full.txt, summary.md    -- generated; regenerate via their own scripts.
  * docs/upstream-gap-report-*   -- records old versions as a historical baseline.
  * "Needed in Cairo <v>" notes  -- factual claims about a past release.
  * Version banners with build hashes/dates -- paste real `scarb --version` output.
EOF
}

while [[ $# -gt 0 ]]; do
	case "$1" in
	--cairo)
		CAIRO_OLD="${2%%:*}"
		CAIRO_NEW="${2##*:}"
		shift 2
		;;
	--foundry)
		FOUNDRY_OLD="${2%%:*}"
		FOUNDRY_NEW="${2##*:}"
		shift 2
		;;
	--dry-run)
		DRY_RUN=1
		shift
		;;
	-h | --help)
		usage
		exit 0
		;;
	*)
		echo "error: unknown argument '$1'" >&2
		usage >&2
		exit 1
		;;
	esac
done

if [[ -z ${CAIRO_OLD} ]] && [[ -z ${FOUNDRY_OLD} ]]; then
	echo "error: at least one of --cairo or --foundry is required" >&2
	usage >&2
	exit 1
fi

for pair in "${CAIRO_OLD}:${CAIRO_NEW}" "${FOUNDRY_OLD}:${FOUNDRY_NEW}"; do
	[[ ${pair} == ":" ]] && continue
	if [[ ! ${pair} =~ ^[0-9]+\.[0-9]+\.[0-9]+:[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
		echo "error: expected OLD:NEW semver pair, got '${pair}'" >&2
		exit 1
	fi
done

echo "=== Version bump ==="
[[ -n ${CAIRO_OLD} ]] && echo "  Cairo/Scarb      ${CAIRO_OLD} -> ${CAIRO_NEW}"
[[ -n ${FOUNDRY_OLD} ]] && echo "  Starknet Foundry ${FOUNDRY_OLD} -> ${FOUNDRY_NEW}"
[[ ${DRY_RUN} -eq 1 ]] && echo "  (dry run -- no files will be written)"
echo

CHANGED_LIST=""
CHANGED_COUNT=0

# apply <file> <perl-expr>
#
# Runs the substitution against a scratch copy first so that a file is only
# reported (and only rewritten) when the expression actually matches.
apply() {
	local file="$1" expr="$2"
	[[ -f ${file} ]] || return 0

	local tmp
	tmp="$(mktemp)"
	perl -pe "${expr}" "${file}" >"${tmp}"

	if cmp -s "${file}" "${tmp}"; then
		rm -f "${tmp}"
		return 0
	fi

	if [[ ${DRY_RUN} -eq 1 ]]; then
		rm -f "${tmp}"
	else
		cat "${tmp}" >"${file}"
		rm -f "${tmp}"
	fi

	CHANGED_LIST+="${file}"$'\n'
	CHANGED_COUNT=$((CHANGED_COUNT + 1))
}

# Version strings appear inside `// Needed in Cairo X.Y.Z because ...` comments,
# which are statements about a historical release and must survive the bump.
GUARD='next if /Needed in Cairo/;'

# ---------------------------------------------------------------------------
# 1. .tool-versions
# ---------------------------------------------------------------------------
echo "--- .tool-versions ---"
[[ -n ${CAIRO_OLD} ]] && apply .tool-versions "s/^scarb \Q${CAIRO_OLD}\E\$/scarb ${CAIRO_NEW}/"
[[ -n ${FOUNDRY_OLD} ]] && apply .tool-versions "s/^starknet-foundry \Q${FOUNDRY_OLD}\E\$/starknet-foundry ${FOUNDRY_NEW}/"

# ---------------------------------------------------------------------------
# 2. Manifests: Scarb.toml (Cairo packages) and Cargo.toml (procedural macros)
#
# Crate versions are pinned as `name = "X.Y.Z"`, sometimes with a range operator
# (`starknet = ">=2.16.1"`). snforge_std tracks the Foundry release; every other
# pinned crate tracks the compiler release.
#
# `*_Scarb.toml` catches ch01's `initial_Scarb.toml`, which is not a real
# manifest but is included verbatim in the book.
# ---------------------------------------------------------------------------
echo "--- manifests ---"
CAIRO_CRATES='cairo_execute|cairo_test|assert_macros|starknet|cairo-lang-[a-z-]+'

while IFS= read -r -d '' manifest; do
	if [[ -n ${CAIRO_OLD} ]]; then
		apply "${manifest}" \
			"s/^(\s*(?:${CAIRO_CRATES})\s*=\s*\"[><=^~]*)\Q${CAIRO_OLD}\E\"/\${1}${CAIRO_NEW}\"/"
	fi
	if [[ -n ${FOUNDRY_OLD} ]]; then
		apply "${manifest}" \
			"s/^(\s*snforge_std\s*=\s*\"[><=^~]*)\Q${FOUNDRY_OLD}\E\"/\${1}${FOUNDRY_NEW}\"/"
	fi
done < <(find listings runner_crate ./Scarb.toml -maxdepth 4 \
	\( -name book -o -name .git -o -name node_modules -o -name target \) -prune -o \
	\( -name Scarb.toml -o -name Cargo.toml -o -name '*_Scarb.toml' \) -type f \
	-print0 2>/dev/null | sort -zu)

# ---------------------------------------------------------------------------
# 3. Prose and code fences
#
# docs/upstream-gap-report-*.md deliberately records the pre-bump versions as
# the baseline it is comparing against, so it is excluded.
# ---------------------------------------------------------------------------
echo "--- prose ---"
while IFS= read -r -d '' doc; do
	case "${doc}" in
	*/upstream-gap-report-*) continue ;;
	*) ;; # every other doc is fair game
	esac

	if [[ -n ${CAIRO_OLD} ]]; then
		# `cairo_execute = "2.16.1"` in fenced manifest snippets
		apply "${doc}" \
			"${GUARD} s/((?:${CAIRO_CRATES})\s*=\s*)\"\Q${CAIRO_OLD}\E\"/\${1}\"${CAIRO_NEW}\"/g"
		# `scarb 2.16.1` / `Scarb 2.16.1` / `cairo: 2.16.1` / `version 2.16.1`
		apply "${doc}" \
			"${GUARD} s/\b(scarb|Scarb|cairo:|Cairo|version)(\s+)\Q${CAIRO_OLD}\E\b/\${1}\${2}${CAIRO_NEW}/g"
		# crates.io and GitHub URLs carrying the version
		apply "${doc}" \
			"${GUARD} s{(cairo-lang-compiler/)\Q${CAIRO_OLD}\E}{\${1}${CAIRO_NEW}}g"
	fi

	if [[ -n ${FOUNDRY_OLD} ]]; then
		apply "${doc}" \
			"s/(snforge_std\s*=\s*)\"\Q${FOUNDRY_OLD}\E\"/\${1}\"${FOUNDRY_NEW}\"/g"
		apply "${doc}" \
			"s/\b(snforge|starknet-foundry|version)(\s+)\Q${FOUNDRY_OLD}\E\b/\${1}\${2}${FOUNDRY_NEW}/g"
	fi
done < <(find src docs CLAUDE.md README.md -name '*.md' -type f \
	-not -path '*/book/*' -not -path '*/node_modules/*' \
	-print0 2>/dev/null | sort -zu)

# ---------------------------------------------------------------------------
# 4. Helper scripts that emit manifest lines
# ---------------------------------------------------------------------------
echo "--- scripts ---"
if [[ -n ${CAIRO_OLD} ]]; then
	apply scripts/handle_targets.py \
		"s/((?:${CAIRO_CRATES})\s*=\s*)\\\\?\"\Q${CAIRO_OLD}\E\\\\?\"/\${1}\"${CAIRO_NEW}\"/g"
fi

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo
echo "=== Summary ==="
if [[ ${CHANGED_COUNT} -eq 0 ]]; then
	echo "No files matched. Are the old versions correct?"
else
	printf '%s' "${CHANGED_LIST}" | sort -u | sed 's/^/  /'
	echo
	echo "  ${CHANGED_COUNT} substitution pass(es) across $(printf '%s' "${CHANGED_LIST}" | sort -u | wc -l | tr -d ' ') file(s)."
fi

cat <<EOF

Follow-up steps this script does NOT perform:
  1. Regenerate lockfiles:  find listings -name Scarb.toml -execdir scarb fetch \\;
  2. Paste real toolchain output into src/ch01-01-installation.md
     (the banner carries a build hash, date and sierra version).
  3. Verify:   cairo-listings verify && cairo-listings format && typos
  4. Rebuild generated artifacts:  mdbook build && scripts/combine-markdown.sh
EOF

[[ ${DRY_RUN} -eq 1 ]] && echo && echo "Dry run: nothing was written."
exit 0
