[[questions]]
id = "aac32d9f-b5a4-4946-81f2-eb6bcfc090ed"
type = "ShortAnswer"
prompt.prompt = "What is the name of the initial function that a Cairo program runs?"
answer.answer = "main"

[[questions]]
id = "a89b37cf-aa75-4fc7-b433-3b57d273ce1d"
type = "ShortAnswer"
prompt.prompt = "Which command will run the code in your project?"
answer.answer = "scarb cairo-run"
context = "`scarb cairo-run` will first compile and then run your code."
