[[questions]]
id = "17e3db31-79aa-44b6-9dc2-be8b37b83ada"
type = "MultipleChoice"
prompt.prompt = "Which syntax creates a variable that can be reassigned?"
answer.answer = """
```rust
let mut x = 99;
```
"""
prompt.distractors = [
"""
```rust
const MINUTES_PER_HOUR = 60;
```
""",
"""
```rust
let y = 10;
```
"""
]

[[questions]]
id = "0a902a6d-3fca-4d72-b455-5e9ab12441d9"
type = "MultipleChoice"
prompt.prompt = """
What will be the output of the following program?
```rust
fn main() {
    let initial_balance = 9;
    let initial_balance = initial_balance - 3;
    {
        let initial_balance = initial_balance * 2;
    }
    println!("Final balance is: {}", initial_balance);
}
```
"""
answer.answer = "`Final balance is: 6`"
prompt.distractors = [
  "`Final balance is: 12`",
  "The program won't compile."
]
