[[questions]]
type = "Tracing"
prompt.program = """
#[derive(Drop)]
struct Character {
    health: felt252,
    attack: felt252,
}

impl CharacterSub of Sub<Character> {
    fn sub(p1: Character, p2: Character) -> Character{
        Character { health: p1.health - p2.attack, attack: p1.attack}
    }
}


fn main() {
    let mut player1: Character = Character { health: 100, attack: 2};
    let player2: Character = Character { health: 100, attack: 5};
    player1 = player1 - player2;
     println!("{}", player1.health); 
}
"""
answer.doesCompile = false
context = "When implementing a trait, the parameter names in the implementing function must match the parameter names specified in the trait definition."