[package]
name = "no_listing_99_02_explicit_internal_fn"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
# foo = { path = "vendor/foo" }
starknet = ">=2.3.0-rc0"
