[package]
name = "listing_03_test_component"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = ">=2.11.4"

[dev-dependencies]
cairo_test = "2.11.4"
