[package]
name = "no_listing_06_assert"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[cairo]
enable-gas = false

[dependencies]
cairo_execute = "2.11.4"

[dev-dependencies]
snforge_std = "0.44.0"
assert_macros = "2.11.4"

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]


[[target.executable]]
name = "main"
function = "no_listing_06_assert::main"
