[package]
name = "listing_inline_macros"
version = "0.1.0"
edition = "2024_07"

# ANCHOR: feature_flag
experimental-features = ["user_defined_inline_macros"]
# ANCHOR_END: feature_flag

[cairo]

[dependencies]
cairo_execute = "2.13.1"

[dev-dependencies]
snforge_std = "0.51.1"
assert_macros = "2.13.1"

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]
