[package]
name = "listing_01_ownable"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
starknet = ">=2.9.1"

[[target.starknet-contract]]
